const projects = [
  {
    name: "Feedbackjar",
    url: "https://feedbackjar.app",
    description: "Open source feedback, roadmaps and changelogs",
    thumbnail: "/projects/feedbackjar.png",
    status: "WIP",
  },
  {
    name: "Formdata",
    url: "https://formdata.cc",
    description: "Relay form data to your email for free",
    thumbnail: "/projects/formdata.png",
    status: "Active",
  },
  {
    name: "Feedful",
    url: "https://feedful.aoo",
    description: "Modern news reader in tweetdeck style",
    thumbnail: "/projects/feedful.png",
    status: "Active",
  },
  {
    name: "Simple Online Tools",
    url: "https://simpleonline.tools",
    description: "Simple online tools for everyday use",
    thumbnail: "/projects/simpleonline-tools.png",
    status: "WIP",
  },
  {
    name: "Imbox",
    url: "https://dub.sh/imbox",
    description: "Temporary inbox as a chrome extension",
    thumbnail: "/projects/imbox.png",
    status: "Active",
  },
  {
    name: "Iconbuddy",
    url: "https://iconbuddy.app",
    description: "200k+ open source icons in one place",
    thumbnail: "/projects/iconbuddy.png",
    status: "Acquired",
  },
  {
    name: "Postperfect",
    url: "https://postperfect.xyz",
    description: "Chatgpt for your tweets",
    thumbnail: "/projects/postperfect.png",
    status: "Acquired",
  },
  {
    name: "Fluenticons",
    url: "https://fluenticons.co",
    description: "Microsoft fluenticons viewer",
    thumbnail: "/projects/fluenticons.png",
    status: "Acquired",
  },
  {
    name: "Appydev",
    url: "https://appydev.co",
    description: "Tools for designers and developers",
    thumbnail: "/projects/appydev.png",
    status: "Active",
  },
  {
    name: "Tvflix",
    url: "https://tvflix.netlify.app",
    description: "IPTV player with 100K+ tv stations in browser",
    thumbnail: "/projects/tvflix.png",
    status: "Dead",
  },
  {
    name: "Gitstars",
    url: "",
    description: "Better github trending page",
    thumbnail: "/projects/gitstars.png",
    status: "Dead",
  },
];
